name: Auto label
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: bdougie/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
