on: pull_request_review
name: label pull requests on reviews
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
